services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://your-username:your-password@cluster.mongodb.net/expense-tracker
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-here
      - key: PORT
        value: 10000
